### ISSUE TITLE
Yaw 

### ISSUE THREAD

**Issue by VanbecelaereVincent** [mnltake/gpsnavi#3]
Hello,

I'm currently working on a project using reinforcement learning to make two roombas play a game against eachother. And i'm looking at the MPU6050 sensor to acquire perfect positioning (yaw and distance). Saw you were working on something similar so I thought I'd maybe ask you a question. 

I'm using the same repo for calibration and getting yaw values as you: https://github.com/mnltake/MPU6050-I2C-Python-Class

So I calibrate my sensor and read the yaw using 'DMP_get_euler_roll_pitch_yaw(quat, grav)' function. But these values seem to fluctuate from time to time. And also does this return just simply the value in degrees? Because this doens't seem to be the case to me. Also I feel like calibration doesn't work properly. Do you have any thoughts on this? 

Sincerely yours!

Vincent

**Comment by VanbecelaereVincent** [comment]
@mnltake

**Comment by mnltake** [comment]
Hello,Vincent
I just fork, so I do not understand it in detail
But,maybe this page may be helpful for you
https://github.com/kriswiner/MPU6050/wiki/Affordable-9-DoF-Sensor-Fusion
